export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const ProductDetailsLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  // if (true) {
  //   throw new Error("my error")
  // }
  return (
    <>
      {children}
      <h2>Features product</h2>
    </>
  )
}

export default ProductDetailsLayout;